import { StyleSheet, Dimensions } from 'react-native';

const { width } = Dimensions.get('window');

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#FFFFFF',
  },
  scrollContent: {
    paddingBottom: 40,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 24,
    paddingTop: 60,
    paddingBottom: 20,
    backgroundColor: '#FFFFFF',
  },
  backBtn: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#F8FAFC',
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerTitle: {
    fontSize: 16,
    fontFamily: 'Lexend',
    fontWeight: '700',
    color: '#FF794A',
    letterSpacing: 1,
  },
  optionsBtn: {
    width: 40,
    height: 40,
    alignItems: 'center',
    justifyContent: 'center',
  },
  heroSection: {
    marginHorizontal: 24,
    marginTop: 20,
    height: 192,
    borderRadius: 24,
    backgroundColor: '#F3F4F3',
    overflow: 'hidden',
    position: 'relative',
    padding: 32,
    justifyContent: 'center',
  },
  heroImageContainer: {
    position: 'absolute',
    right: -20,
    top: -20,
    opacity: 0.2,
  },
  heroTitle: {
    fontSize: 30,
    fontFamily: 'Lexend',
    fontWeight: '800',
    color: '#191C1C',
    lineHeight: 38,
  },
  heroSub: {
    fontSize: 14,
    fontFamily: 'Manrope',
    fontWeight: '500',
    color: '#584235',
    marginTop: 8,
    lineHeight: 20,
    width: '60%',
  },
  sectionContainer: {
    paddingHorizontal: 24,
    marginTop: 32,
  },
  sectionHeader: {
    fontSize: 13,
    fontFamily: 'Lexend',
    fontWeight: '600',
    color: '#94A3B8',
    letterSpacing: 2,
    textTransform: 'uppercase',
    marginBottom: 16,
  },
  bentoGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    gap: 16,
  },
  bentoCard: {
    width: (width - 48 - 16) / 2,
    height: 140,
    borderRadius: 16,
    backgroundColor: '#F8FAFC',
    padding: 16,
    borderWidth: 2,
    borderColor: 'transparent',
  },
  bentoCardSelected: {
    borderColor: '#FF794A',
    backgroundColor: '#FFFFFF',
    shadowColor: '#FF794A',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 12,
    elevation: 4,
  },
  cardIconContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 12,
  },
  checkCircle: {
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: '#FF794A',
    alignItems: 'center',
    justifyContent: 'center',
  },
  emptyCircle: {
    width: 20,
    height: 20,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#CBD5E1',
  },
  cardTitle: {
    fontSize: 18,
    fontFamily: 'Lexend',
    fontWeight: '700',
    color: '#191C1C',
    marginBottom: 4,
  },
  cardSub: {
    fontSize: 12,
    fontFamily: 'Manrope',
    fontWeight: '500',
    color: '#64748B',
    lineHeight: 16,
  },
  allergyList: {
    gap: 12,
  },
  allergyItem: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#F8FAFC',
    padding: 16,
    borderRadius: 16,
  },
  allergyIconBox: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: '#EEF2F6',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 16,
  },
  allergyInfo: {
    flex: 1,
  },
  allergyName: {
    fontSize: 16,
    fontFamily: 'Lexend',
    fontWeight: '600',
    color: '#191C1C',
  },
  allergySub: {
    fontSize: 12,
    fontFamily: 'Manrope',
    color: '#64748B',
    marginTop: 2,
  },
  updateBtn: {
    marginHorizontal: 24,
    marginTop: 40,
    height: 56,
    borderRadius: 28,
    backgroundColor: '#FF794A',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#FF794A',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.3,
    shadowRadius: 16,
    elevation: 8,
  },
  updateBtnText: {
    fontSize: 16,
    fontFamily: 'Lexend',
    fontWeight: '700',
    color: '#FFFFFF',
  },
  footerNote: {
    textAlign: 'center',
    fontSize: 11,
    fontFamily: 'Manrope',
    fontWeight: '600',
    color: '#94A3B8',
    marginTop: 24,
    paddingHorizontal: 40,
    lineHeight: 16,
    textTransform: 'uppercase',
  }
});
