import { StyleSheet, Dimensions, Platform } from 'react-native';

const { width } = Dimensions.get('window');

const colors = {
  primary: '#FF7849',
  brandOrange: '#A8390D',
  brandBrown: '#58423B',
  onyx: '#1B1B1E',
  success: '#10B981',
  warning: '#FBBF24',
  danger: '#EF4444',
  background: '#FBF8FC',
  white: '#FFFFFF',
  inputBg: '#F6F2F7',
  gray: '#94A3B8',
  slate: '#CBD5E1',
  border: 'rgba(223, 192, 182, 0.10)',
};

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.white,
  },
  header: {
    height: 83,
    backgroundColor: colors.background,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 24,
    paddingTop: Platform.OS === 'ios' ? 42 : 20,
    zIndex: 10,
  },
  headerLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 16,
  },
  headerIcon: {
    width: 24,
    height: 24,
    justifyContent: 'center',
    alignItems: 'center',
  },
  headerTitle: {
    fontSize: 24,
    fontWeight: '700',
    color: colors.brandOrange,
    fontFamily: 'Manrope',
    lineHeight: 32,
  },
  headerProfile: {
    width: 32,
    height: 32,
    backgroundColor: colors.brandOrange,
    borderRadius: 4, // Square-ish in snippet
    justifyContent: 'center',
    alignItems: 'center',
  },
  scrollContent: {
    paddingHorizontal: 24,
    paddingTop: 16,
    paddingBottom: 200, // Extra space for FAB and Bottom Tabs
  },
  // Tab Switcher
  tabSwitcher: {
    width: '100%',
    padding: 4,
    backgroundColor: colors.inputBg,
    borderRadius: 48,
    flexDirection: 'row',
    gap: 8,
    marginBottom: 24,
  },
  tabButton: {
    flex: 1,
    paddingVertical: 8,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 24,
  },
  activeTabButton: {
    backgroundColor: colors.white,
    shadowColor: 'rgba(0, 0, 0, 0.05)',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 1,
    shadowRadius: 2,
    elevation: 2,
  },
  tabText: {
    fontSize: 14,
    fontFamily: 'Inter',
    fontWeight: '500',
    color: colors.brandBrown,
    lineHeight: 20,
  },
  activeTabText: {
    fontWeight: '700',
    color: colors.brandOrange,
  },
  // Nutrition Summary
  summaryCard: {
    width: '100%',
    height: 162,
    padding: 24,
    backgroundColor: colors.white,
    borderRadius: 24,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderWidth: 1,
    borderColor: colors.border,
    shadowColor: 'rgba(0, 0, 0, 0.05)',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 1,
    shadowRadius: 2,
    elevation: 1,
    marginBottom: 12,
  },
  circleContainer: {
    width: 112,
    height: 112,
    justifyContent: 'center',
    alignItems: 'center',
    position: 'relative',
  },
  circleBackground: {
    position: 'absolute',
    width: 100,
    height: 100,
    borderRadius: 50,
    borderWidth: 8,
    borderColor: colors.inputBg,
  },
  circleValueContainer: {
    position: 'absolute',
    width: 112,
    height: 112,
    justifyContent: 'center',
    alignItems: 'center',
  },
  circleValue: {
    fontSize: 20,
    fontFamily: 'Manrope',
    fontWeight: '800',
    color: colors.onyx,
    lineHeight: 20,
  },
  circleLabel: {
    fontSize: 9,
    fontFamily: 'Inter',
    fontWeight: '400',
    color: colors.brandBrown,
    textTransform: 'uppercase',
    lineHeight: 13.5,
  },
  statsContainer: {
    flex: 1,
    paddingLeft: 32,
    gap: 4,
  },
  goalLabel: {
    fontSize: 14,
    fontFamily: 'Inter',
    fontWeight: '400',
    color: colors.brandBrown,
    textTransform: 'uppercase',
    lineHeight: 20,
    letterSpacing: 1.4,
  },
  goalValueMain: {
    flexDirection: 'row',
    alignItems: 'baseline',
  },
  goalValue: {
    fontSize: 24,
    fontFamily: 'Manrope',
    fontWeight: '700',
    color: colors.onyx,
    lineHeight: 32,
  },
  goalUnit: {
    fontSize: 12,
    fontFamily: 'Manrope',
    fontWeight: '400',
    color: colors.onyx,
    lineHeight: 16,
    marginLeft: 4,
  },
  bottomStats: {
    flexDirection: 'row',
    gap: 16,
    paddingTop: 4,
  },
  statBox: {
    gap: 0,
  },
  statLabel: {
    fontSize: 10,
    fontFamily: 'Inter',
    fontWeight: '400',
    color: colors.brandBrown,
    lineHeight: 15,
  },
  statValue: {
    fontSize: 16,
    fontFamily: 'Inter',
    fontWeight: '700',
    lineHeight: 24,
  },
  // Macros Card
  macrosCard: {
    width: '100%',
    padding: 20,
    backgroundColor: colors.inputBg,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: colors.border,
    gap: 8,
    marginBottom: 24,
  },
  macroRow: {
    width: '100%',
    gap: 8,
    marginBottom: 8,
  },
  macroHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-end',
  },
  macroLabel: {
    fontSize: 10,
    fontFamily: 'Inter',
    fontWeight: '400',
    color: colors.brandBrown,
    textTransform: 'uppercase',
    lineHeight: 15,
  },
  macroValue: {
    fontSize: 12,
    fontFamily: 'Inter',
    fontWeight: '700',
    color: colors.onyx,
    lineHeight: 16,
  },
  macroProgressBar: {
    width: '100%',
    height: 6,
    backgroundColor: '#E4E1E6',
    borderRadius: 9999,
    overflow: 'hidden',
  },
  macroProgressFill: {
    height: '100%',
    borderRadius: 9999,
  },
  // Today's Meals Section
  mealsSectionHeader: {
    width: '100%',
    paddingTop: 8,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
  },
  mealsSectionTitle: {
    fontSize: 24,
    fontFamily: 'Manrope',
    fontWeight: '700',
    color: colors.onyx,
    lineHeight: 32,
  },
  addFoodLink: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  addFoodIcon: {
    width: 16,
    height: 16,
    //backgroundColor: colors.brandOrange,
    borderRadius: 2,
  },
  addFoodText: {
    fontSize: 14,
    fontFamily: 'Inter',
    fontWeight: '600',
    color: colors.brandOrange,
    lineHeight: 20,
  },
  // Meal Card
  mealCard: {
    width: '100%',
    padding: 24,
    backgroundColor: colors.inputBg,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: 'rgba(223, 192, 182, 0.05)',
    shadowColor: 'rgba(0, 0, 0, 0.05)',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 1,
    shadowRadius: 2,
    elevation: 1,
    marginBottom: 24,
    gap: 16,
  },
  mealCardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
  },
  mealTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 16,
  },
  mealIconContainer: {
    width: 48,
    height: 48,
    borderRadius: 16,
    justifyContent: 'center',
    alignItems: 'center',
  },
  mealInfoContainer: {
    // flex auto
  },
  mealTypeTitle: {
    fontSize: 18,
    fontFamily: 'Manrope',
    fontWeight: '700',
    color: colors.onyx,
    lineHeight: 28,
  },
  mealMetaContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  mealTimeText: {
    fontSize: 12,
    fontFamily: 'Inter',
    fontWeight: '500',
    color: colors.brandBrown,
    lineHeight: 16,
  },
  mealDotSeparator: {
    width: 4,
    height: 4,
    backgroundColor: '#DFC0B6',
    borderRadius: 9999,
  },
  mealMacrosMeta: {
    fontSize: 12,
    fontFamily: 'Inter',
    fontWeight: '500',
    color: colors.success,
    lineHeight: 16,
  },
  mealCalorieContainer: {
    alignItems: 'flex-end',
  },
  mealCalorieValue: {
    fontSize: 20,
    fontFamily: 'Manrope',
    fontWeight: '700',
    color: colors.brandOrange,
    lineHeight: 28,
  },
  mealCalorieLabel: {
    fontSize: 10,
    fontFamily: 'Inter',
    fontWeight: '400',
    color: colors.brandBrown,
    textTransform: 'uppercase',
    lineHeight: 15,
    letterSpacing: 1,
  },
  mealDivider: {
    width: '100%',
    height: 1,
    backgroundColor: 'rgba(223, 192, 182, 0.10)',
    marginTop: 0,
  },
  foodItemsList: {
    width: '100%',
    gap: 12,
  },
  foodItemRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  foodItemTextGroup: {
    flex: 1,
  },
  foodItemName: {
    fontSize: 14,
    fontFamily: 'Inter',
    fontWeight: '500',
    color: colors.onyx,
    lineHeight: 20,
  },
  foodItemWeight: {
    fontSize: 11,
    fontFamily: 'Inter',
    fontWeight: '400',
    color: colors.brandBrown,
    lineHeight: 16.5,
  },
  foodItemKcal: {
    fontSize: 14,
    fontFamily: 'Inter',
    fontWeight: '600',
    color: colors.onyx,
    lineHeight: 20,
  },
  // Empty Meal Log
  notLoggedCard: {
    opacity: 0.7,
  },
  logMealAction: {
    width: '100%',
    paddingVertical: 10,
    borderRadius: 48,
    borderWidth: 1,
    borderColor: '#DFC0B6',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 8,
  },
  logMealIconBox: {
    width: 8,
    height: 8,
    backgroundColor: colors.brandOrange,
  },
  logMealActionText: {
    fontSize: 14,
    fontFamily: 'Inter',
    fontWeight: '700',
    color: colors.brandOrange,
    lineHeight: 20,
  },
  // Common FAB Container (Absolute positioned in the screen)
  fabContainer: {
    position: 'absolute',
    left: 24,
    right: 24,
    bottom: 120, // Will adjust if bottom tabs are visible
  },
  mainLogMealFab: {
    width: '100%',
    height: 56,
    backgroundColor: colors.onyx,
    borderRadius: 9999,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 8,
    // Add Shadow
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.1,
    shadowRadius: 10,
    elevation: 8,
  },
  fabIconWrapper: {
    width: 20,
    height: 20,
    //backgroundColor: colors.background,
  },
  fabLabel: {
    fontSize: 16,
    fontFamily: 'Manrope',
    fontWeight: '700',
    color: colors.background,
    lineHeight: 24,
  },
  // Weekly Schedule Styles
  weeklyScheduleContainer: {
    marginTop: 8,
  },
  weeklyHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 20,
  },
  weeklyTitle: {
    fontSize: 24,
    fontFamily: 'Manrope',
    fontWeight: '700',
    color: colors.onyx,
  },
  viewAllLink: {
    fontSize: 14,
    fontFamily: 'Inter',
    fontWeight: '600',
    color: colors.brandOrange,
  },
  dateSelector: {
    marginBottom: 24,
  },
  dateSelectorContent: {
    paddingRight: 24,
  },
  dayItem: {
    width: 60,
    height: 80,
    backgroundColor: '#F6F2F7',
    borderRadius: 20,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  dayItemActive: {
    backgroundColor: colors.brandOrange,
    shadowColor: colors.brandOrange,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 4,
  },
  dayName: {
    fontSize: 12,
    fontFamily: 'Inter',
    fontWeight: '500',
    color: colors.brandBrown,
    marginBottom: 4,
  },
  dayNameActive: {
    color: 'rgba(255, 255, 255, 0.8)',
  },
  dateNumber: {
    fontSize: 18,
    fontFamily: 'Manrope',
    fontWeight: '700',
    color: colors.onyx,
  },
  dateNumberActive: {
    color: colors.white,
  },
  activeDot: {
    width: 4,
    height: 4,
    backgroundColor: colors.white,
    borderRadius: 2,
    marginTop: 4,
  },
  // Plan Empty State
  planEmptyState: {
    padding: 32,
    backgroundColor: '#F6F2F7',
    borderRadius: 32,
    alignItems: 'center',
    gap: 16,
    marginTop: 20,
  },
  emptyStateTitle: {
    fontSize: 18,
    fontFamily: 'Manrope',
    fontWeight: '700',
    color: colors.onyx,
    textAlign: 'center',
  },
  emptyStateDesc: {
    fontSize: 14,
    fontFamily: 'Inter',
    color: colors.brandBrown,
    textAlign: 'center',
    lineHeight: 20,
  },
  generatePlanButton: {
    marginTop: 12,
    backgroundColor: colors.brandOrange,
    paddingHorizontal: 24,
    paddingVertical: 14,
    borderRadius: 28,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  generatePlanButtonText: {
    color: colors.white,
    fontSize: 16,
    fontFamily: 'Manrope',
    fontWeight: '700',
  },
  generateNewPlanBtn: {
    width: '100%',
    height: 56,
    borderRadius: 28,
    backgroundColor: colors.onyx,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
    marginTop: 24,
  },
  generateNewPlanBtnText: {
    color: '#FBF8FC',
    fontSize: 16,
    fontFamily: 'Manrope',
    fontWeight: '700',
    textTransform: 'uppercase',
  },
});
