import { StyleSheet, Dimensions, Platform } from 'react-native';
import { colors } from '../../theme/colors';

const { width } = Dimensions.get('window');
const isWeb = Platform.OS === 'web';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#FFFFFF',
    ...(isWeb && {
      maxWidth: 1200,
      marginHorizontal: 'auto',
      width: '100%',
    }),
  },
  content: {
    flex: 1,
    paddingTop: 5, // Matches the top absolute offset from design
    paddingHorizontal: 0,
    ...(isWeb && {
      paddingHorizontal: 40,
      paddingTop: 60,
      paddingBottom: 40,
      maxWidth: 800,
      marginHorizontal: 'auto',
    }),
  },
  headerTopBar: {
    marginTop: 30,
    height: 55,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 24,
    backgroundColor: 'rgba(255, 255, 255, 0.9)',
    zIndex: 10,
  },
  headerTitleContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  backButton: {
    marginRight: 16,
    justifyContent: 'center',
    alignItems: 'center',
  },
  headerTitle: {
    color: '#EA580C',
    fontSize: 24,
    fontWeight: '900',
    textTransform: 'uppercase',
  },
  stepContainer: {
    flex: 1,
    paddingHorizontal: 24,
    paddingTop: 10,
  },
  editorialHeaderSection: {
    marginTop: 0,
    marginBottom: 48,
  },
  mainTitle: {
    color: '#1F2937', // Or #2C2F31
    fontSize: 48,
    fontWeight: '800',
    lineHeight: 52,
    textTransform: 'uppercase',
  },
  mainSubtitle: {
    color: '#6B7280', // Or #595C5E
    fontSize: 18,
    fontWeight: '500',
    lineHeight: 28,
    marginTop: 8,
  },
  avatarContainer: {
    width: 128,
    height: 128,
    borderRadius: 64,
    backgroundColor: '#DFE3E6',
    alignSelf: 'flex-start',
    marginBottom: 48,
    position: 'relative',
    justifyContent: 'center',
    alignItems: 'center',
  },
  avatarImage: {
    width: '100%',
    height: '100%',
    borderRadius: 64,
  },
  avatarCameraIcon: {
    position: 'absolute',
    bottom: 0,
    right: 0,
    width: 46,
    height: 44,
    backgroundColor: '#FF794A',
    borderRadius: 22,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 3,
    borderColor: '#FFFFFF',
    elevation: 3,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
  },
  inputFieldsContainer: {
    gap: 24,
    marginBottom: 40,
  },
  inputContainer: {
    flexDirection: 'column',
    gap: 8,
  },
  inputLabel: {
    fontSize: 12,
    fontWeight: '700',
    color: '#595C5E',
    marginLeft: 8,
    textTransform: 'uppercase',
  },
  inputWrapper: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#EEF1F3', // Input background
    borderRadius: 9999, // Pill shape
    paddingHorizontal: 24,
    height: 68,
  },
  textInput: {
    flex: 1,
    fontSize: 18,
    fontWeight: '500',
    color: '#374151',
  },
  inputUnit: {
    color: '#374151',
    fontSize: 12,
    fontWeight: '700',
    marginLeft: 8,
  },
  multilineInput: {
    height: 120,
    borderRadius: 24,
    paddingTop: 24,
    textAlignVertical: 'top',
  },
  pickerContainer: {
    backgroundColor: '#EEF1F3',
    borderRadius: 9999,
    overflow: 'hidden',
    height: 68,
    justifyContent: 'center',
    paddingHorizontal: 12,
  },
  picker: {
    height: '100%',
    width: '100%',
  },
  genderContainer: {
    flexDirection: 'column',
    gap: 16,
    marginBottom: 40,
  },
  genderButtonsRow: {
    flexDirection: 'row',
    gap: 12,
  },
  genderButton: {
    flex: 1,
    height: 52,
    borderRadius: 9999,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#D9DDE0',
  },
  genderButtonActive: {
    backgroundColor: '#FF794A',
  },
  genderButtonText: {
    fontSize: 14,
    fontWeight: '700',
    color: '#2C2F31',
  },
  genderButtonTextActive: {
    color: '#451000', // Deep brown/orange
  },
  sectionTitleContainer: {
    marginBottom: 16,
  },
  sectionTitle: {
    fontSize: 12,
    fontWeight: '700',
    color: '#6B7280',
    marginLeft: 8,
    textTransform: 'uppercase',
  },
  goalsWrapper: {
    gap: 12,
  },
  goalCard: {
    backgroundColor: '#F1F3F5',
    borderRadius: 32,
    padding: 20,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderWidth: 2,
    borderColor: 'transparent',
  },
  goalCardSelected: {
    backgroundColor: '#FFF3EF',
    borderColor: '#FF7043',
  },
  goalTextContainer: {
    flex: 1,
  },
  goalTitle: {
    color: '#1F2937',
    fontSize: 18,
    fontWeight: '800',
    marginBottom: 4,
  },
  goalDescription: {
    color: '#4B5563',
    fontSize: 14,
    fontWeight: '400',
  },
  goalIconContainer: {
    width: 40,
    height: 40,
    justifyContent: 'center',
    alignItems: 'center',
  },
  stepBadgeContainer: {
    backgroundColor: '#FFF3EF',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 9999,
    alignSelf: 'flex-start',
    marginBottom: 16,
  },
  stepBadgeText: {
    color: '#FF7043',
    fontSize: 10,
    fontWeight: '800',
    letterSpacing: 1,
  },
  levelTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  levelTitleBlack: {
    color: '#1F2937',
    fontSize: 48,
    fontWeight: '800',
    lineHeight: 52,
    textTransform: 'uppercase',
  },
  levelTitleOrange: {
    color: '#FF794A',
    fontSize: 48,
    fontWeight: '800',
    lineHeight: 52,
    textTransform: 'uppercase',
  },
  levelCard: {
    backgroundColor: '#F1F3F5',
    borderRadius: 32,
    padding: 24,
    marginBottom: 16,
    borderWidth: 2,
    borderColor: 'transparent',
    position: 'relative',
    overflow: 'hidden',
  },
  levelCardSelected: {
    backgroundColor: '#FFFFFF',
    borderColor: '#FF7043',
    shadowColor: '#FF7043',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 12,
    elevation: 4,
  },
  levelIconCircle: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: '#FFFFFF',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 16,
  },
  levelIconCircleSelected: {
    backgroundColor: '#DA5A2E',
  },
  levelTitle: {
    color: '#1F2937',
    fontSize: 20,
    fontWeight: '900',
    marginBottom: 4,
  },
  levelDescription: {
    color: '#6B7280',
    fontSize: 15,
    fontWeight: '500',
  },
  recommendedBadge: {
    position: 'absolute',
    top: 24,
    right: 24,
    backgroundColor: '#FF794A',
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 12,
  },
  recommendedBadgeText: {
    color: '#FFFFFF',
    fontSize: 10,
    fontWeight: '900',
  },
  fixedActionBottomArea: {
    position: 'absolute',
    bottom: 0,
    width: '100%',
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 24,
    paddingTop: 24,
    paddingBottom: Platform.OS === 'ios' ? 34 : 24,
    alignItems: 'center',
    borderTopWidth: 1,
    borderTopColor: 'rgba(0,0,0,0.05)',
  },
  nextButton: {
    backgroundColor: '#FF794A',
    width: '100%',
    paddingVertical: 20,
    borderRadius: 9999,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#FF794A',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.3,
    shadowRadius: 16,
    elevation: 8,
    marginBottom: 24,
  },
  nextButtonDisabled: {
    opacity: 0.5,
  },
  nextButtonText: {
    color: '#000000',
    fontSize: 20,
    fontWeight: '900',
    textTransform: 'uppercase',
  },
  completeButtonText: {
    color: '#000000',
    fontSize: 18,
    fontWeight: '800',
    textTransform: 'uppercase',
  },
  paginationContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  paginationDotActive: {
    width: 32,
    height: 4,
    borderRadius: 2,
    backgroundColor: '#FF794A',
  },
  paginationDotInactive: {
    width: 16,
    height: 4,
    borderRadius: 2,
    backgroundColor: '#E5E7EB',
  },
});
