import { StyleSheet, Dimensions, Platform } from 'react-native';

const { width } = Dimensions.get('window');

const fitlifeColors = {
  brandOrange: '#A8390D',
  accentOrange: '#FF7849',
  softBackground: '#F6F2F7',
  accentPeach: '#FFDBD0',
  onyx: '#1B1B1E',
  grayText: '#5E5E5E',
  white: '#FFFFFF',
  borderLight: '#EAE7EB',
  darkBurgundy: '#681C00',
  brownText: '#8C7169',
  peachDeep: '#FFE8E1',
};

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: fitlifeColors.white,
  },
  // Header
  header: {
    backgroundColor: fitlifeColors.softBackground,
    paddingTop: Platform.OS === 'ios' ? 44 : 20,
    borderBottomLeftRadius: 37,
    borderBottomRightRadius: 37,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.05,
    shadowRadius: 10,
    elevation: 3,
    zIndex: 10,
  },
  headerTop: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 24,
    paddingVertical: 26,
  },
  brandContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  logoImage: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: fitlifeColors.softBackground,
    justifyContent: 'center',
    alignItems: 'center',
    overflow: 'hidden',
  },
  brandName: {
    fontSize: 32,
    fontWeight: '800',
    color: fitlifeColors.brandOrange,
    fontFamily: 'Inter',
    letterSpacing: -0.5,
  },

  // Premium Tab Switcher (Balanced Capsules)
  tabContainer: {
    flexDirection: 'row',
    paddingHorizontal: 24,
    paddingBottom: 24,
    gap: 12,
    justifyContent: 'center',
    alignItems: 'center',
  },
  tab: {
    flex: 1,
    height: 46,
    paddingHorizontal: 8,
    borderRadius: 9999,
    borderWidth: 1,
    borderColor: '#D2C9C9',
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'row',
    gap: 4,
  },
  activeTab: {
    backgroundColor: fitlifeColors.peachDeep,
    borderColor: fitlifeColors.brandOrange,
    shadowColor: fitlifeColors.brandOrange,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
  },
  tabText: {
    fontSize: 13,
    fontWeight: '700',
    color: fitlifeColors.grayText,
    fontFamily: 'Inter',
  },
  activeTabText: {
    color: fitlifeColors.brandOrange,
  },

  // Tab-specific overrides if needed
  tabPlans: { borderColor: '#94A3B8' },
  tabHistory: {},
  tabWorkouts: {},

  content: {
    flex: 1,
  },
  scrollContent: {
    paddingBottom: 140,
  },
  loadingContainer: {
    padding: 100,
    alignItems: 'center',
  },

  // --- PLAN SECTION ---
  activePlanCard: {
    padding: 28,
    backgroundColor: fitlifeColors.brandOrange,
    borderRadius: 37,
    marginHorizontal: 24,
    marginTop: 24,
    overflow: 'hidden',
    position: 'relative',
    shadowColor: fitlifeColors.brandOrange,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.15,
    shadowRadius: 15,
    elevation: 10,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.2)',
  },
  blob1: { width: 220, height: 220, borderRadius: 110, backgroundColor: 'rgba(255,255,255,0.12)', position: 'absolute', top: -110, right: -60 },
  blob2: { width: 180, height: 180, borderRadius: 90, backgroundColor: 'rgba(255,255,255,0.08)', position: 'absolute', bottom: -80, left: -40 },
  planBadge: { alignSelf: 'flex-start', paddingHorizontal: 12, paddingVertical: 6, backgroundColor: 'rgba(255,255,255,0.2)', borderRadius: 12, marginBottom: 16 },
  planBadgeText: { fontSize: 10, fontWeight: '800', color: fitlifeColors.white, letterSpacing: 1.2, textTransform: 'uppercase' },
  planTitle: { fontSize: 30, fontWeight: '800', color: fitlifeColors.white, marginBottom: 8, fontFamily: 'Manrope' },
  planSubtitle: { fontSize: 13, fontWeight: '500', color: fitlifeColors.white, opacity: 0.85, textTransform: 'uppercase', marginBottom: 28, letterSpacing: 0.5 },
  startTodayButton: { backgroundColor: fitlifeColors.white, paddingVertical: 14, paddingHorizontal: 28, borderRadius: 20, alignSelf: 'flex-start', shadowColor: '#000', shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.1, shadowRadius: 8, elevation: 4 },
  startTodayText: { fontWeight: '800', color: fitlifeColors.brandOrange, fontSize: 15 },

  progressSection: { marginHorizontal: 24, marginTop: 32 },
  progressHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 12, paddingHorizontal: 4 },
  sectionTitleSmall: { fontSize: 18, fontWeight: '700', color: fitlifeColors.onyx, fontFamily: 'Manrope' },
  progressStats: { fontSize: 13, color: fitlifeColors.grayText, fontWeight: '600' },
  progressBarContainer: { height: 10, backgroundColor: 'rgba(168, 57, 13, 0.05)', borderRadius: 5, overflow: 'hidden' },
  progressBarFill: { height: '100%', borderRadius: 5 },

  todayPlanSection: { marginHorizontal: 24, marginTop: 40 },
  sectionTitle: { fontSize: 22, fontWeight: '700', color: fitlifeColors.onyx, marginBottom: 20, fontFamily: 'Manrope', paddingHorizontal: 4 },
  todayPlanCard: { backgroundColor: fitlifeColors.peachDeep, borderRadius: 37, padding: 28, shadowColor: fitlifeColors.brandOrange, shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.05, shadowRadius: 8, elevation: 3 },
  todayPlanCore: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start' },
  todayPlanInfo: { flex: 1 },
  todayPlanTitle: { fontSize: 24, fontWeight: '800', color: fitlifeColors.darkBurgundy, marginBottom: 10, fontFamily: 'Manrope' },
  todayPlanDesc: { fontSize: 15, color: 'rgba(104, 28, 0, 0.7)', flex: 1, marginRight: 16, lineHeight: 22 },
  playButtonContainer: { width: 52, height: 52, backgroundColor: fitlifeColors.white, borderRadius: 26, justifyContent: 'center', alignItems: 'center', shadowColor: fitlifeColors.brandOrange, shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.1, shadowRadius: 8, elevation: 5 },
  categoryBadge: { alignSelf: 'flex-start', paddingHorizontal: 10, paddingVertical: 5, backgroundColor: 'rgba(168,57,13,0.08)', borderRadius: 10, marginBottom: 10 },
  categoryBadgeText: { fontSize: 11, fontWeight: '800', color: fitlifeColors.brandOrange, textTransform: 'uppercase', letterSpacing: 0.5 },

  statsRow: { flexDirection: 'row', justifyContent: 'space-between', marginTop: 32 },
  statItem: { alignItems: 'center', flex: 1 },
  statIconContainer: { width: 44, height: 44, borderRadius: 22, backgroundColor: 'rgba(255, 255, 255, 0.5)', justifyContent: 'center', alignItems: 'center', marginBottom: 10 },
  statValue: { fontSize: 16, fontWeight: '800', color: fitlifeColors.darkBurgundy },
  statLabel: { fontSize: 11, fontWeight: '600', color: 'rgba(104, 28, 0, 0.5)', textTransform: 'uppercase', letterSpacing: 1 },

  // --- HISTORY SECTION ---
  historyMainContainer: { paddingTop: 32, paddingHorizontal: 24, paddingBottom: 130 },
  performanceGallery: { marginBottom: 48 },
  galleryLabel: { fontSize: 12, fontWeight: '400', color: fitlifeColors.brownText, textTransform: 'uppercase', letterSpacing: 2.4, marginBottom: 8 },
  galleryTitle: { fontSize: 48, fontWeight: '800', color: fitlifeColors.onyx, lineHeight: 48, fontFamily: 'Manrope', marginBottom: 32 },
  titleAccent: { color: fitlifeColors.brandOrange },
  filterToggle: { flexDirection: 'row', backgroundColor: fitlifeColors.softBackground, borderRadius: 9999, padding: 6, alignSelf: 'flex-start', marginBottom: 24 },
  filterBtn: { paddingHorizontal: 32, paddingVertical: 10, borderRadius: 9999 },
  filterBtnActive: { backgroundColor: fitlifeColors.brandOrange, shadowColor: fitlifeColors.brandOrange, shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.2, shadowRadius: 6, elevation: 4 },
  filterBtnText: { fontSize: 14, fontWeight: '700', color: fitlifeColors.grayText },
  filterBtnTextActive: { color: fitlifeColors.white },
  chartCard: { width: '100%', height: 192, backgroundColor: fitlifeColors.white, borderRadius: 32, padding: 32, shadowColor: '#000', shadowOffset: { width: 0, height: 1 }, shadowOpacity: 0.05, shadowRadius: 2, elevation: 2, borderWidth: 1, borderColor: 'rgba(223, 192, 182, 0.1)' },
  chartInfoOverlay: { position: 'absolute', left: 33, top: 25, zIndex: 5 },
  weeklyVolumeLabel: { fontSize: 10, fontWeight: '700', color: fitlifeColors.grayText, textTransform: 'uppercase', letterSpacing: 1, marginBottom: 1 },
  volumeRow: { flexDirection: 'row', alignItems: 'baseline' },
  volumeValue: { fontSize: 24, fontWeight: '900', color: fitlifeColors.onyx },
  volumeUnit: { fontSize: 14, fontWeight: '700', color: fitlifeColors.brownText, marginLeft: 4 },
  barsRow: { flex: 1, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-end', height: 64 },
  barTrack: { flex: 1, marginHorizontal: 3, backgroundColor: fitlifeColors.accentPeach, borderTopLeftRadius: 6, borderTopRightRadius: 6 },
  barActive: { backgroundColor: fitlifeColors.brandOrange, shadowColor: fitlifeColors.brandOrange, shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.1, shadowRadius: 6, elevation: 2 },
  chartFade: { position: 'absolute', bottom: 0, left: 0, right: 0, height: 95, borderBottomLeftRadius: 32, borderBottomRightRadius: 32 },

  recentSessions: { width: '100%' },
  sessionListTitle: { fontSize: 22, fontWeight: '700', color: fitlifeColors.onyx, marginBottom: 24, paddingHorizontal: 4, fontFamily: 'Manrope' },
  sessionCard: { width: '100%', backgroundColor: fitlifeColors.peachDeep, borderRadius: 32, padding: 24, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 16 },
  sessionContent: { flex: 1, marginRight: 16 },
  sessionDate: { fontSize: 11, fontWeight: '700', color: 'rgba(168, 57, 13, 0.7)', textTransform: 'uppercase', letterSpacing: 1.1, marginBottom: 4 },
  sessionTitle: { fontSize: 24, fontWeight: '800', color: fitlifeColors.darkBurgundy, lineHeight: 32, marginBottom: 12 },
  sessionStats: { flexDirection: 'row', gap: 16 },
  statBit: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  statBitText: { fontSize: 14, fontWeight: '700', color: 'rgba(104, 28, 0, 0.8)' },
  playIconCircle: { width: 64, height: 64, borderRadius: 32, backgroundColor: 'rgba(255, 255, 255, 0.4)', justifyContent: 'center', alignItems: 'center' },

  endOfHistory: { paddingTop: 48, paddingBottom: 32, alignItems: 'center', opacity: 0.4 },
  horizontalLine: { width: 48, height: 4, backgroundColor: '#DFC0B6', borderRadius: 9999, marginBottom: 24 },
  endText: { fontSize: 12, fontWeight: '700', color: fitlifeColors.grayText, textTransform: 'uppercase', letterSpacing: 1.2, marginBottom: 8 },
  endSubtext: { fontSize: 14, color: fitlifeColors.onyx, textAlign: 'center', lineHeight: 20, width: 189 },

  // --- WORKOUT SECTION ---
  searchContainer: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#F8FAFC', marginHorizontal: 24, marginTop: 24, paddingHorizontal: 16, height: 56, borderRadius: 20, borderWidth: 1, borderColor: '#E2E8F0' },
  searchInput: { flex: 1, fontSize: 16, color: '#1E293B', fontWeight: '500' },
  categoryItem: { flexDirection: 'row', alignItems: 'center', backgroundColor: 'white', padding: 24, borderRadius: 32, marginBottom: 16, shadowColor: '#000', shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.05, shadowRadius: 10, elevation: 3, borderWidth: 1, borderColor: 'rgba(223, 192, 182, 0.1)' },
  muscleImageWrapper: { width: 80, height: 80, borderRadius: 20, backgroundColor: fitlifeColors.softBackground, marginRight: 20, overflow: 'hidden' },
  muscleImage: { width: '100%', height: '100%' },
  categoryInfo: { flex: 1 },
  categoryName: { fontSize: 20, fontWeight: '800', color: fitlifeColors.onyx, marginBottom: 6, fontFamily: 'Manrope' },
  categorySubtext: { fontSize: 14, color: fitlifeColors.brownText, fontWeight: '600' },

  // --- MISC ---
  bottomActionContainer: { paddingVertical: 40, alignItems: 'center' },
  generatedBadge: { flexDirection: 'row', alignItems: 'center', gap: 8, backgroundColor: '#FFF7ED', paddingHorizontal: 16, paddingVertical: 8, borderRadius: 20 },
  generatedBadgeText: { fontSize: 11, fontWeight: '800', color: fitlifeColors.brandOrange, letterSpacing: 1 },
  emptyState: { alignItems: 'center', paddingVertical: 80, paddingHorizontal: 40 },
  emptyStateText: { fontSize: 16, color: fitlifeColors.grayText, textAlign: 'center', marginTop: 24, marginBottom: 36, lineHeight: 24 },
  generateButton: { flexDirection: 'row', alignItems: 'center', backgroundColor: fitlifeColors.brandOrange, paddingVertical: 16, paddingHorizontal: 32, borderRadius: 24, gap: 12, shadowColor: fitlifeColors.brandOrange, shadowOffset: { width: 0, height: 10 }, shadowOpacity: 0.2, shadowRadius: 20, elevation: 8 },
  generateButtonText: { color: 'white', fontSize: 17, fontWeight: '800' },

  // High-Fidelity Generate Button (Custom Snippet)
  generateNewPlanContainer: {
    paddingHorizontal: 24,
    paddingVertical: 32,
    alignItems: 'center',
    justifyContent: 'center',
  },
  generateNewPlanButton: {
    width: '100%',
    height: 52,
    paddingHorizontal: 32,
    backgroundColor: 'rgba(168, 57, 13, 0.05)',
    borderRadius: 9999,
    borderWidth: 2,
    borderColor: 'rgba(168, 57, 13, 0.30)',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 12,
  },
  squareIcon: {
    width: 16.5,
    height: 16.5,
    backgroundColor: '#A8390D',
  },
  generateNewPlanText: {
    textAlign: 'center',
    color: '#A8390D',
    fontSize: 14,
    fontFamily: Platform.OS === 'ios' ? 'Inter' : 'sans-serif-medium',
    fontWeight: '700',
    lineHeight: 20,
    letterSpacing: 0.35,
  },
});
