import { StyleSheet, Dimensions, Platform } from 'react-native';

const { width, height } = Dimensions.get('window');

const fitlifeColors = {
  brandOrange: '#A8390D',
  accentOrange: '#FF7849',
  softBackground: '#F6F2F7',
  accentPeach: '#FFDBD0',
  onyx: '#1B1B1E',
  grayText: '#5E5E5E',
  white: '#FFFFFF',
  borderLight: '#EAE7EB',
  darkBurgundy: '#681C00',
  textSecondary: '#58423B',
};

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: fitlifeColors.white,
    ...(Platform.OS === 'web' && {
      maxWidth: 500,
      alignSelf: 'center',
    }),
  },
  // Header
  header: {
    height: 90,
    backgroundColor: fitlifeColors.white,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: width * 0.05,
    paddingTop: Platform.OS === 'ios' ? 40 : 20,
    borderBottomRightRadius: 37,
    borderBottomLeftRadius: 37,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 8,
    zIndex: 100,
  },
  backButton: {
    width: 32,
    height: 32,
    backgroundColor: fitlifeColors.brandOrange,
    borderRadius: 8,
    justifyContent: 'center',
    alignItems: 'center',
  },
  headerTitle: {
    flex: 1,
    textAlign: 'center',
    fontSize: 22,
    fontWeight: '700',
    color: fitlifeColors.onyx,
    fontFamily: Platform.OS === 'ios' ? 'Manrope' : 'sans-serif-medium',
    marginRight: 32, // Balance back button
  },

  content: {
    flex: 1,
  },
  contentContainer: {
    paddingBottom: 160,
  },

  // Media Section
  videoContainer: {
    width: width,
    height: height * 0.3,
    minHeight: 250,
    backgroundColor: 'rgba(166, 166, 166, 0.20)',
    overflow: 'hidden',
  },
  exerciseVideo: {
    width: '100%',
    height: '100%',
  },

  // Dual Tabs
  tabRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: width * 0.05,
    marginTop: 6,
    gap: 12,
  },
  tabCard: {
    flex: 1,
    height: 51,
    backgroundColor: fitlifeColors.white,
    borderRadius: 16,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 5,
  },
  tabCardActive: {
    borderWidth: 1,
    borderColor: fitlifeColors.accentOrange,
  },
  tabCardText: {
    fontSize: 14,
    fontWeight: '600',
    color: fitlifeColors.accentOrange,
    textTransform: 'uppercase',
    letterSpacing: 0.7,
  },

  // Stats Card
  statsCard: {
    width: '90%',
    alignSelf: 'center',
    marginTop: 14,
    backgroundColor: fitlifeColors.accentPeach,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: fitlifeColors.accentOrange,
    paddingVertical: 16,
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
    shadowColor: fitlifeColors.accentOrange,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 3,
  },
  statColumn: {
    alignItems: 'center',
    flex: 1,
  },
  statIconBox: {
    width: 36,
    height: 36,
    backgroundColor: 'rgba(168, 57, 13, 0.1)',
    borderRadius: 18,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 6,
  },
  statLabel: {
    fontSize: 10,
    color: fitlifeColors.onyx,
    textTransform: 'uppercase',
    letterSpacing: 0.7,
    fontWeight: '600',
    marginBottom: 4,
  },
  statValue: {
    fontSize: 18,
    fontFamily: 'Inter',
    fontWeight: '700',
    color: fitlifeColors.brandOrange,
    letterSpacing: 0.7,
  },

  // Set Progress
  progressSection: {
    alignItems: 'center',
    marginTop: 15,
  },
  progressLabel: {
    fontSize: 14,
    fontWeight: '600',
    color: fitlifeColors.grayText,
    textTransform: 'uppercase',
    letterSpacing: 0.7,
    marginBottom: 12,
  },
  dotsRow: {
    flexDirection: 'row',
    gap: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  progressDot: {
    width: 26,
    height: 26,
    borderRadius: 13,
    borderWidth: 2,
    borderColor: '#EAE7EB',
    justifyContent: 'center',
    alignItems: 'center',
  },
  progressDotActive: {
    borderColor: fitlifeColors.accentOrange,
  },
  progressDotInner: {
    width: 10,
    height: 10,
    backgroundColor: fitlifeColors.accentOrange,
    borderRadius: 5,
  },
  progressDotCompleted: {
    backgroundColor: fitlifeColors.brandOrange,
    borderColor: fitlifeColors.brandOrange,
  },

  // Counter
  counterSection: {
    alignItems: 'center'
    ,
  },
  repNumber: {
    fontSize: 72,
    fontWeight: '800',
    color: fitlifeColors.onyx,
    fontFamily: Platform.OS === 'ios' ? 'Manrope' : 'sans-serif-condensed',
    textAlign: 'center',
  },
  repLabel: {
    fontSize: 12,
    color: fitlifeColors.grayText,
    textTransform: 'uppercase',
    letterSpacing: 2.8,
    marginTop: 0,
    marginBottom: 10,
    textAlign: 'center',
  },
  adjustmentRow: {
    flexDirection: 'row',
    gap: 32,
    alignItems: 'center',
    justifyContent: 'center',
  },
  adjButton: {
    width: 48,
    height: 48,
    backgroundColor: fitlifeColors.softBackground,
    borderRadius: 24,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 2,
  },

  // Sticky Actions
  actionContainer: {
    position: 'absolute',
    bottom: 0, left: 0, right: 0,
    backgroundColor: 'rgba(255, 255, 255, 0.9)',
    borderTopLeftRadius: 37,
    borderTopRightRadius: 37,
    paddingHorizontal: width * 0.1,
    paddingTop: 16,
    paddingBottom: Platform.OS === 'ios' ? 24 : 24,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: -4 },
    shadowOpacity: 0.1,
    shadowRadius: 10,
    elevation: 20,
  },
  nextSetButton: {
    width: '100%', height: 54,
    backgroundColor: fitlifeColors.accentOrange,
    borderRadius: 32,
    justifyContent: 'center', alignItems: 'center',
    flexDirection: 'row', gap: 12,
    shadowColor: fitlifeColors.accentOrange,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.2, shadowRadius: 8, elevation: 10,
  },
  nextSetText: { fontSize: 18, fontWeight: '700', color: fitlifeColors.darkBurgundy },
  skipButton: { marginTop: 8, paddingVertical: 8 },
  skipText: { fontSize: 14, fontWeight: '600', color: fitlifeColors.grayText, textTransform: 'uppercase', letterSpacing: 0.35 },

  // --- NEW TIMER STYLES ---
  timerModalOverlay: {
    flex: 1,
    backgroundColor: fitlifeColors.softBackground,
  },
  timerFullContainer: {
    paddingTop: 50,
    flex: 1,
    alignItems: 'center',
  },
  timerModalHeader: {
    width: '100%',
    height: 96,
    backgroundColor: 'rgba(255, 255, 255, 0.8)',
    justifyContent: 'center',
    alignItems: 'center',
    paddingTop: 20,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(0, 0, 0, 0.05)',
  },
  timerHeaderTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: '#18181B',
  },
  timerLabelSet: {
    marginTop: 60,
    alignItems: 'center',
  },
  timerRestTag: {
    fontSize: 12,
    fontWeight: '700',
    color: fitlifeColors.brandOrange,
    textTransform: 'uppercase',
    letterSpacing: 2.4,
    marginBottom: 8,
  },
  timerRecoverTitle: {
    fontSize: 30,
    fontWeight: '800',
    color: fitlifeColors.onyx,
    fontFamily: 'Manrope',
  },
  timerCircleWrapper: {
    width: 250,
    height: 250,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 40,
    position: 'relative',
  },
  timerCircleOuter: {
    position: 'absolute',
    width: 250,
    height: 250,
    borderRadius: 125,
    borderWidth: 12,
    borderColor: '#FFDBD0',
    opacity: 0.3,
  },
  timerCircleInner: {
    width: 218,
    height: 218,
    borderRadius: 109,
    backgroundColor: fitlifeColors.white,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: fitlifeColors.brandOrange,
    shadowOffset: { width: 0, height: 32 },
    shadowOpacity: 0.08,
    shadowRadius: 64,
    elevation: 20,
  },
  timerBigText: {
    fontSize: 64,
    fontWeight: '800',
    color: fitlifeColors.onyx,
    fontFamily: 'Manrope',
  },
  timerExerciseInfo: {
    marginTop: 40,
    alignItems: 'center',
  },
  timerExerciseName: {
    fontSize: 24,
    fontWeight: '800',
    color: fitlifeColors.onyx,
    fontFamily: 'Manrope',
    marginBottom: 8,
  },
  timerExerciseSummary: {
    fontSize: 20,
    fontWeight: '400',
    color: fitlifeColors.textSecondary,
  },
  timerActions: {
    width: width * 0.7,
    marginTop: 60,
    gap: 16,
  },
  extendButton: {
    height: 64,
    backgroundColor: fitlifeColors.accentOrange,
    borderRadius: 32,
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'row',
    gap: 12,
    shadowColor: fitlifeColors.accentOrange,
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.2,
    shadowRadius: 15,
    elevation: 10,
  },
  extendButtonText: {
    fontSize: 16,
    fontWeight: '700',
    color: fitlifeColors.darkBurgundy,
  },
  skipRestBtn: {
    height: 56,
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'row',
    gap: 8,
  },
  skipRestBtnText: {
    fontSize: 16,
    fontWeight: '700',
    color: fitlifeColors.brandOrange,
  },

  // Info Overlays
  infoOverlay: {
    marginTop: 16,
    paddingHorizontal: width * 0.05,
  },
  infoText: {
    fontSize: 15,
    color: fitlifeColors.onyx,
    lineHeight: 24,
    backgroundColor: fitlifeColors.softBackground,
    padding: 24,
    borderRadius: 24,
    overflow: 'hidden',
  }
});
