import { StyleSheet, Dimensions, Platform } from 'react-native';

const { width, height } = Dimensions.get('window');

const colors = {
  primary: '#FF7849',
  brandOrange: '#A8390D',
  peach: '#FFDBD0',
  peachDeep: '#FFE8E1',
  white: '#FFFFFF',
  onyx: '#1B1B1E',
  brown: '#58423B',
  darkBurgundy: '#681C00',
  burgundySoft: '#832600',
  background: '#FBF8FC',
  border: '#DFC0B6',
};

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
  },
  header: {
    width: '100%',
    height: 100,
    paddingTop: Platform.OS === 'ios' ? 50 : 20,
    backgroundColor: colors.background,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 24,
  },
  backButton: {
    position: 'absolute',
    left: 24,
    top: Platform.OS === 'ios' ? 55 : 25,
    width: 32,
    height: 32,
    justifyContent: 'center',
    alignItems: 'center',
  },
  backIcon: {
    width: 14,
    height: 14,
    backgroundColor: colors.brandOrange,
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: colors.onyx,
    fontFamily: 'Manrope',
  },
  content: {
    flex: 1,
    alignItems: 'center',
    paddingHorizontal: 24,
  },
  successSection: {
    alignItems: 'center',
    marginTop: 20,
    marginBottom: 40,
  },
  iconCircle: {
    width: 151,
    height: 151,
    borderRadius: 75.5,
    backgroundColor: colors.peach,
    justifyContent: 'center',
    alignItems: 'center',
    overflow: 'hidden',
  },
  successImage: {
    width: '100%',
    height: '100%',
    position: 'absolute',
    opacity: 0.8,
  },
  iconInner: {
    width: 64,
    height: 61,
    backgroundColor: colors.brandOrange,
    borderRadius: 10,
  },
  congratsTitle: {
    fontSize: 36,
    fontWeight: '800',
    color: colors.onyx,
    fontFamily: 'Manrope',
    textAlign: 'center',
    marginTop: 24,
    lineHeight: 44,
  },
  congratsSubtitle: {
    fontSize: 16,
    fontWeight: '500',
    color: colors.brown,
    fontFamily: 'Inter',
    textAlign: 'center',
    marginTop: 12,
    lineHeight: 24,
  },
  statsCard: {
    width: '100%',
    backgroundColor: colors.peachDeep,
    borderRadius: 32,
    padding: 32,
    paddingLeft: 45,
    position: 'relative',
    overflow: 'hidden',
  },
  statsBlurBlob: {
    width: 160,
    height: 160,
    borderRadius: 80,
    backgroundColor: colors.primary,
    position: 'absolute',
    right: -40,
    bottom: -40,
    opacity: 0.1,
  },
  statGroup: {
    marginBottom: 20,
  },
  statLastGroup: {
    marginBottom: 0,
  },
  statLabel: {
    fontSize: 10,
    fontWeight: '700',
    color: colors.burgundySoft,
    fontFamily: 'Inter',
    textTransform: 'uppercase',
    letterSpacing: 1,
    opacity: 0.6,
  },
  statValueRow: {
    flexDirection: 'row',
    alignItems: 'baseline',
    marginTop: 4,
    gap: 4,
  },
  statValue: {
    fontSize: 36,
    fontWeight: '800',
    color: colors.burgundySoft,
    fontFamily: 'Manrope',
  },
  statUnit: {
    fontSize: 12,
    fontWeight: '600',
    color: colors.burgundySoft,
    fontFamily: 'Inter',
  },
  footer: {
    paddingHorizontal: 24,
    paddingBottom: Platform.OS === 'ios' ? 40 : 24,
    gap: 16,
  },
  primaryButton: {
    width: '100%',
    height: 64,
    backgroundColor: colors.primary,
    borderRadius: 32,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: colors.primary,
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.2,
    shadowRadius: 15,
    elevation: 8,
  },
  primaryButtonText: {
    fontSize: 18,
    fontWeight: '700',
    color: colors.darkBurgundy,
    fontFamily: 'Manrope',
  },
  secondaryButton: {
    width: '100%',
    height: 64,
    borderRadius: 32,
    borderWidth: 2,
    borderColor: colors.border,
    justifyContent: 'center',
    alignItems: 'center',
  },
  secondaryButtonText: {
    fontSize: 18,
    fontWeight: '700',
    color: colors.brown,
    fontFamily: 'Manrope',
  },
});
