import { StyleSheet, Dimensions, Platform } from 'react-native';

const { width } = Dimensions.get('window');

const colors = {
  primary: '#FF7849',
  brandOrange: '#A8390D',
  peach: '#FFDBD0',
  peachDeep: '#FFE8E1',
  white: '#FFFFFF',
  onyx: '#1B1B1E',
  gray: '#5E5E5E',
  grayLite: '#94A3B8',
  border: '#DFC0B633',
  inputBg: '#F6F2F7',
  burgundySoft: '#832600',
  darkBurgundy: '#390C00',
};

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.white,
  },
  header: {
    height: Platform.OS === 'ios' ? 100 : 70,
    backgroundColor: colors.inputBg,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 24,
    paddingTop: Platform.OS === 'ios' ? 40 : 0,
    borderBottomLeftRadius: 32,
    borderBottomRightRadius: 32,
    zIndex: 10,
  },
  backButton: {
    padding: 8,
    borderRadius: 9999,
  },
  headerTitle: {
    flex: 1,
    textAlign: 'center',
    fontSize: 18,
    fontWeight: '700',
    color: colors.brandOrange,
    fontFamily: 'Manrope',
    marginRight: 40,
  },
  scrollContainer: {
    flex: 1,
  },
  scrollContent: {
    padding: 24,
    paddingTop: 32,
    paddingBottom: 120, // Space for sticky button
    gap: 40,
  },
  heroSection: {
    gap: 8,
  },
  heroLabel: {
    fontSize: 10,
    fontWeight: '700',
    color: colors.brandOrange,
    textTransform: 'uppercase',
    letterSpacing: 1.5,
    fontFamily: 'Inter',
    opacity: 0.8,
  },
  heroTitle: {
    fontSize: 36,
    fontWeight: '800',
    color: colors.onyx,
    lineHeight: 45,
    fontFamily: 'Manrope',
    marginBottom: 16,
  },
  summaryCard: {
    flexDirection: 'row',
    backgroundColor: colors.white,
    borderRadius: 32,
    padding: 24,
    alignItems: 'center',
    gap: 20,
    borderWidth: 1,
    borderColor: 'rgba(223, 192, 182, 0.2)',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.05,
    shadowRadius: 10,
    elevation: 3,
  },
  summaryIconCircle: {
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: colors.peach,
    justifyContent: 'center',
    alignItems: 'center',
  },
  summaryInfo: {
    flex: 1,
  },
  summaryTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: colors.onyx,
    fontFamily: 'Manrope',
    marginBottom: 4,
  },
  summaryText: {
    fontSize: 14,
    color: colors.gray,
    fontFamily: 'Inter',
    opacity: 0.8,
  },
  section: {
    gap: 20,
  },
  sectionTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: colors.onyx,
    fontFamily: 'Manrope',
  },
  vibeRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  vibeItem: {
    alignItems: 'center',
    gap: 8,
  },
  emojiContainer: {
    width: 56,
    height: 56,
    borderRadius: 28,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: colors.inputBg,
  },
  emojiSelected: {
    backgroundColor: colors.primary,
    borderWidth: 4,
    borderColor: colors.peach,
    shadowColor: colors.primary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 6,
  },
  emojiText: {
    fontSize: 32,
    lineHeight: 40,
  },
  vibeLabel: {
    fontSize: 10,
    fontWeight: '700',
    color: colors.grayLite,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    fontFamily: 'Inter',
  },
  vibeLabelSelected: {
    color: colors.brandOrange,
    fontWeight: '900',
  },
  intensityOptions: {
    flexDirection: 'row',
    gap: 12,
  },
  intensityPill: {
    flex: 1,
    paddingVertical: 14,
    borderRadius: 9999,
    borderWidth: 2,
    borderColor: colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  intensityPillSelected: {
    backgroundColor: colors.primary,
    shadowColor: colors.primary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 6,
    elevation: 4,
  },
  intensityPillText: {
    fontSize: 14,
    fontWeight: '700',
    color: colors.primary,
    fontFamily: 'Manrope',
  },
  intensityPillTextSelected: {
    color: colors.white,
  },
  notesInput: {
    width: '100%',
    minHeight: 140,
    backgroundColor: colors.inputBg,
    borderRadius: 24,
    padding: 20,
    fontSize: 16,
    color: colors.onyx,
    fontFamily: 'Inter',
    textAlignVertical: 'top',
  },
  footer: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    padding: 24,
    paddingBottom: Platform.OS === 'ios' ? 34 : 24,
    backgroundColor: 'rgba(255, 255, 255, 0.9)',
    borderTopLeftRadius: 32,
    borderTopRightRadius: 32,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: -4 },
    shadowOpacity: 0.05,
    shadowRadius: 10,
    elevation: 10,
  },
  saveButton: {
    width: '100%',
    height: 64,
    backgroundColor: colors.primary,
    borderRadius: 32,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: colors.primary,
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.2,
    shadowRadius: 12,
    elevation: 8,
  },
  saveButtonText: {
    fontSize: 18,
    fontWeight: '900',
    color: colors.white,
    textTransform: 'uppercase',
    letterSpacing: 2,
    fontFamily: 'Manrope',
  },
  consistencyCard: {
    borderRadius: 32,
    overflow: 'hidden',
    marginTop: 8,
  },
  streakImage: {
    width: '100%',
    height: 160,
  },
  streakInfo: {
    backgroundColor: colors.peach,
    padding: 24,
    paddingBottom: 32,
    borderBottomLeftRadius: 32,
    borderBottomRightRadius: 32,
    position: 'relative',
    overflow: 'hidden',
  },
  streakTitle: {
    fontSize: 24,
    fontWeight: '700',
    color: colors.darkBurgundy,
    lineHeight: 30,
    fontFamily: 'Manrope',
  },
  streakText: {
    fontSize: 12,
    color: colors.burgundySoft,
    lineHeight: 18,
    fontFamily: 'Inter',
    marginTop: 8,
    opacity: 0.9,
  },
  streakIconBox: {
    position: 'absolute',
    right: 20,
    top: 20,
    opacity: 0.15,
  },
});
